/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Compte;
import bean.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultEditorKit;
import service.CompteService;
import service.UserService;
import util.Session;

/**
 *
 * @author ayoub
 */
public class CompteCreateView extends javax.swing.JFrame {

    CompteService compteService = new CompteService();
    UserService userService = new UserService();

    /**
     * Creates new form compteCreateView
     */
    public CompteCreateView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        logField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prenomField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        telephoneField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adresseArea = new javax.swing.JTextArea();
        passwordField = new javax.swing.JPasswordField();
        confermatioPasswordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 24))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 408));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("login :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 70, 21);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inscription");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 10, 150, 30);

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);
        saveButton.setBounds(550, 430, 58, 25);
        jPanel1.add(logField);
        logField.setBounds(200, 50, 130, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("nom :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 220, 37, 21);
        jPanel1.add(nomField);
        nomField.setBounds(200, 210, 130, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 73, 21);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("prenom :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 170, 59, 21);
        jPanel1.add(prenomField);
        prenomField.setBounds(200, 170, 130, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("confermation password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 166, 21);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("rôle :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 260, 50, 20);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--", "Administrateur", "Standard" }));
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(roleComboBox);
        roleComboBox.setBounds(200, 250, 190, 30);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("telephone");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 64, 21);

        telephoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(telephoneField);
        telephoneField.setBounds(200, 400, 170, 30);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("adresse :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 300, 65, 21);

        adresseArea.setColumns(20);
        adresseArea.setRows(5);
        jScrollPane1.setViewportView(adresseArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 290, 400, 96);
        jPanel1.add(passwordField);
        passwordField.setBounds(200, 90, 130, 30);
        jPanel1.add(confermatioPasswordField);
        confermatioPasswordField.setBounds(200, 130, 130, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\messagerieEntreEmployes\\Image\\Creation.jpg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 640, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Compte compte = getParam();
        User user = getParam1();
        try {
            if (compte.getPassword().equals(compte.getConfermationPassword())) {
                compte.setConnexion("horsligne");
                int res = compteService.save(compte);
                
                userService.save(user);

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC SUCCES", "info", JOptionPane.INFORMATION_MESSAGE);
                    
                    this.setVisible(false);
                    new ConnexionView().setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "LA CONFIRMATION DU MOT DE PASSE EST INCORECTTE", "ereur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC ERROR", "ereur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveButtonActionPerformed
    private User getParam1() {
        User user = new User();
        user.setId(logField.getText());
        user.setPasword(passwordField.getText());
        user.getCompte().setId(logField.getText());
        return user;
    }

    private Compte getParam() {
        Compte compte = new Compte();
        compte.setId(logField.getText());
        compte.setNom(nomField.getText());
        compte.setPrenom(prenomField.getText());
        compte.setPassword(passwordField.getText());
        compte.setConfermationPassword(confermatioPasswordField.getText());
        compte.setAdresse(adresseArea.getText());
        compte.setRole(roleComboBox.getSelectedItem() + "");
        compte.setTelMob(new Long(telephoneField.getText()));
       
       
        return compte;
    }

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void telephoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompteCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompteCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompteCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompteCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompteCreateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adresseArea;
    private javax.swing.JPasswordField confermatioPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField logField;
    private javax.swing.JTextField nomField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField prenomField;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField telephoneField;
    // End of variables declaration//GEN-END:variables

}
