/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Compte;
import bean.User;
import dao.CompteDao;
import helper.CompteHelper;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.CompteService;
import service.UserService;
import util.Session;

/**
 *
 * @author ayoub
 */
public class ConnexionView extends javax.swing.JFrame {

    CompteHelper compteHelper;
    UserService userservice = new UserService();
    CompteService compteService = new CompteService();

    /**
     * Creates new form seConnecterCreateView
     */
    public ConnexionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        connexionButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Authentification");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 10, 187, 34);

        loginField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(loginField);
        loginField.setBounds(250, 120, 190, 40);

        passwordField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(passwordField);
        passwordField.setBounds(250, 170, 190, 40);

        loginLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("LOGIN");
        jPanel1.add(loginLabel);
        loginLabel.setBounds(150, 130, 80, 21);

        passwordLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("PASSWORD");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(150, 180, 90, 21);

        connexionButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        connexionButton.setText("CONNEXION");
        connexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connexionButton);
        connexionButton.setBounds(440, 220, 140, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\messagerieEntreEmployes\\Image\\13995745-verrouillage-ic-ne-maison.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 140, 70, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\messagerieEntreEmployes\\Image\\Authentification.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 679, 350);

        loginField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginField1.setForeground(new java.awt.Color(255, 255, 255));
        loginField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginField1ActionPerformed(evt);
            }
        });
        jPanel1.add(loginField1);
        loginField1.setBounds(250, 120, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionButtonActionPerformed
        try {
            User myUser = userservice.seConnecter(getParam());
            if (myUser == null) {
                JOptionPane.showMessageDialog(null, "PROBLEME DE CONNEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                Session.updateAttribute(myUser, "user");
                this.setVisible(false);

                CompteDao compteDao = new CompteDao();
                myUser.getCompte().setConnexion("enligne");
                compteDao.update(myUser.getCompte());
                new BoiteMessage().setVisible(true);

//                String requette = "update Compte SET connexion = 6 where id like " +loginField.getText()+"'";
//                compteService.execUpdate(requette);
//               List<Compte> Comptes;
//               ProfilView profilView = new ProfilView();
//                   compteHelper = new CompteHelper(profilView.jTable1, comptes);
//                System.out.println(myUser.getCompte().getId()+"yyyyyyyyyyyyy");
            }
        } catch (Exception ex) {
            Logger.getLogger(ConnexionView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_connexionButtonActionPerformed
    private User getParam() {
        User user = new User();
        user.setId(loginField.getText());
        user.setPasword(passwordField.getText());
        return user;
    }
    private void loginField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connexionButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField loginField1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables

}
