/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Compte;
import bean.Message;
import bean.User;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.CompteService;
import service.MessageService;
import util.Session;

/**
 *
 * @author ayoub
 */
public class NouveauMessage extends javax.swing.JFrame {

    MessageService messageService = new MessageService();

    CompteService compteService = new CompteService();

    private void initCombobox() throws Exception {

        contactsComboBox.removeAllItems();
        contactsComboBox.addItem("--SELECT CONTACT--");
        List<Compte> comptes = compteService.findAll();
        for (Compte item : comptes) {
            contactsComboBox.addItem(item.getId());
        }

    }

    private void initView() throws Exception {
        initCombobox();
    }

    /**
     * Creates new form ChatEntreEmploye
     */
    public NouveauMessage() {
        initComponents();
        try {
            initView();
        } catch (Exception ex) {
            Logger.getLogger(NouveauMessage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        contactsComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(641, 361));

        jPanel1.setPreferredSize(new java.awt.Dimension(641, 361));
        jPanel1.setLayout(null);

        inputTextArea.setColumns(20);
        inputTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        inputTextArea.setRows(5);
        jScrollPane3.setViewportView(inputTextArea);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(50, 148, 380, 130);

        sendButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        sendButton.setText("ENVOYER");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sendButton);
        sendButton.setBounds(450, 170, 130, 96);

        contactsComboBox.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        contactsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactsComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(contactsComboBox);
        contactsComboBox.setBounds(200, 80, 224, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Envoyer à :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 80, 80, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\messagerieEntreEmployes\\Image\\NouveauMessage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactsComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_contactsComboBoxActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
           // TODO add your handling code here:

            Message message = getParem();
            if(!contactsComboBox.getSelectedItem().equals("--SELECT CONTACT--")){
                
            
            
            int res = messageService.save(message);
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "MESSAGE ENVOYE AVEC SUCCES", "info", JOptionPane.INFORMATION_MESSAGE);
            }
            this.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Selectioner un contact", "info", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(true);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "MESSAGE NON ENVOYE", "ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private Message getParem() {
        Message message = new Message();
        User myUser = (User) Session.getAttribut("user");
        message.getCompte().setId(contactsComboBox.getSelectedItem()+"");
        message.setCorps(inputTextArea.getText());
        message.setIdEmetteur(myUser.getCompte().getId());
        message.setEtatLecture("Non lu");
        
        return message;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouveauMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouveauMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox contactsComboBox;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables

}
